# zhaopin-auto config
zhilian:
  cityCode: "广州"
  salary: "0,5000"
  keywords:
    - "供应链实习"
    - "跨境物流"
    - "数据分析"
    - "物流管理实习"
    - "冷链物流"
    - "仓储管理实习"
    - "电商运营实习"
    - "供应链管理"
    - "商业分析实习"
    - "数据运营"
    - "产品实习"
    - "策略分析实习"
    - "采购实习"
    - "智慧物流"
    - "管理咨询实习"

bot:
  is_send: false
